### ISSUE TITLE
Web page with the most used Git commands

### ISSUE THREAD

**Issue by Kelex21** [namruthahari/Sample-Git-Repo#10]
I propose to create a basic web page where people can see the most used git commands when working on a project.

This page may have:
- The command
- Explanation of the command
- Example of the command

**Comment by namruthahari** [comment]
Sure! That is a great idea!

**Comment by Kelex21** [comment]
@namruthahari, We should agree, people who also want to contribute could come in and contribute little by little

**Comment by Kelex21** [comment]
I'll try to work on it ...

**Comment by Korak-997** [comment]
@Kelex21 did you start building the webpage ? 

when i checked the Repo i had the same idea. Would be happy if i can participate in :)

and if you did not start the project yet , maybe we can start it together ?
what you think @namruthahari ?

**Comment by Kelex21** [comment]
No, I haven't started.
@Korak-997  I think it's a good idea, any help is welcome.

I think @namruthahari  will be happy to get us started, and anyone who wants to contribute can join.
The idea is to create something basic and improve it.
@namruthahari you can open a project? to keep track of what we are doing.

A design can be created in Figma.
When the design is done we can share it to start with the layout.

**Comment by Kelex21** [comment]
The idea of the **project** is as follows:

- A page with the most used **Git** **commands**.
- Explanation of the **command**.
- Example of how to use the **command**.

Then implement a section where people will be shown how to contribute to a **project** with **Git** & **Github** (If possible using **images**).

Feel free to give your opinion, any idea or improvement is welcome.

**Comment by Korak-997** [comment]
I love the Idea :) and am in :stuck_out_tongue: 

I can even open a Repo in my account , and then you guys can join me . 
Or you guys want to have it on your accounts ?

I basically do not have a problem either ways :smile: 

From coding i can do that part , even kind of advanced also . But would be nicer if you two come up with the design because i really do not have that much time to do the design .

We can kind of make a online meeting also if you two are interested to talk about everything comfortably .

**Comment by Korak-997** [comment]
We can kind of make a online meeting also if you to are interested to talk about everything comfortably .

**Comment by Kelex21** [comment]
We can talk on **Discord**. This is my user:
About where the project is hosted I have no problem. for my part I just want to contribute. Either in this repository or in your repository @Korak-997.

Regarding communication we can organize ourselves a little better in **discord**, of course if you have an account.
I remain open to any ideas. **Have a nice day**.

**Comment by Korak-997** [comment]
Great i will try to reach out on Discord :) hope @namruthahari will join also :)

**Comment by Kelex21** [comment]
What a fool, I did not write my username = (
My username: Kelex21#6494

**Comment by Korak-997** [comment]
Am gonna reach out soon :+1:

**Comment by datta-soumil** [comment]
Guys I would also like to help you let's team up and create an amazing repo together @Kelex21 @namruthahari @korak-997

**Comment by namruthahari** [comment]
@Korak-997 @Kelex21 @datta-soumil 
Woah! You guys had a grand discussion. This is a great plan!
I am beginner at WebDev and am willing to learn though. 
My username is Namz#7802,
Let's get this project started 🔥🔥🔥

**Comment by Korak-997** [comment]
Hey i did send you all friend request on discord @Kelex21 @datta-soumil @namruthahari 
Am not sure if i sent it correctly please answer me with text there 🙂 so i can start a group

**Comment by datta-soumil** [comment]
@Korak-997 
I just received it buddy and I have accepted too

**Comment by Korak-997** [comment]
Cool 🙂 now @Kelex21 is still missing i am gonna get him in when he answers me
